#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "[POLICY] You can't commit directly to master branch"
  exit 1
fi

if [ "$branch" = "development" ]; then
  echo "[POLICY] You can't commit directly to development branch"
  exit 1
fi